---
title: "The American Civil War as Political Event"
author: "Jonathan Obert"
format: pdf
editor: visual
bibliography: references.bib
---

## Introduction

The American Civil War (ACW) is, without a doubt, the single most significant event in US political history. Beyond its immediate destruction and devastation, the war led to the expansion of citizenship and enfranchisement rights to Black men, the creation of a new constitutional system founded on federal guarantees for due process and the incorporation of constitutional protections, the construction of a new currency and banking system, the entrenchment of the Republican party, the opening of the territorial trans-Mississippi West to political incorporation in the Union, and a dramatically expanded state bureaucracy.

But what does it mean to call the ACW an "event?" In a critical sense - as many historians have recently concluded - the ACW was not merely a collection of violent confrontations between North and South between 1861 and 1865, but rather a multi-dimensional reorganization of the nation's political landscape extending through Reconstruction and beyond [@sinhaRiseFallSecond2024; @richardsonHowSouthWon2022]. This generally takes the form of focusing on the transformative effects of the war on the social, economic, and political organization of the nation (as well as its place in the world) [@benselYankeeLeviathanOrigins1990; @mooreSocialOriginsDictatorship1993; @downsSecondAmericanRevolution2019] or on the way in which the critical legal and constitutional changes of the thirteenth, fourteenth, and fifteenth Amendments generated the (ultimately failed) promise of racial democracy and federal protection for civil rights [@amarBillRightsCreation2008; @fonerSecondFoundingHow2019]. Regardless of how the specifics, in these interpretations the *fighting* of the war itself is often viewed somewhat as a sideshow, less a transformative event on its on terms and instead a pathway to a new structure of national politics.

This essay takes a somewhat different tack. While acknowledging the permeable temporal and conceptual boundaries of the "Civil War" as a reorganization of American life, it tries to understand how the actual process of violence of the war's many encounters concatenated into political and social transformation. Rather than focus on the myriad *effects* of the war, that is, it tries to explain the way in which specific localized encounters, larger coordinated battles, and larger strategic operations articulated into a cluster of changes we call an "event."

As such, this essay draws on two, somewhat disconnected bodies of scholarly inquiry. The first is comparative analytic approaches to thinking about time and change in society. Sociologists, historians, and political scientists have all focused much attention on the question of how social structures - durable patterns and distributions of social relationships, resources, and rules - are transformed by specific transformative events - temporary occurrences that concatenate or articulate into structural change - in specific historical conjunctures - moments at which multiple structures collide or encounter one another. These approaches have

In many ways, then, this essay builds on a long tradition of scholarship on how "wars make states" [@tillyCoercionCapitalEuropean1990]. Some scholars - in particular @benselYankeeLeviathanOrigins1990 - have used this framework to make sense of wartime mobilization as a political reorganization of institutions.

First, are the micro-mechanisms whereby fighting on the battlefield, deployment and mobilization of troops, coordinating movement and managing the internal progression of warfighting concatenates into larger social transformation. The state-building processes of wartime mobilization of resources and forging of administration are ultimately not isolated but are driven by connections between the temporal and spatial flow of organizing a sustained military effort.

The ACW was an extremely complex "hybrid" conflict, with conventional set piece battles, mass mobilized armies, a vast, multi-theater canvas for operations, a naval and commerce raiding component, guerrilla and partisan fighting, and an increasingly sophisticated garrison strategy for holding and ultimately "reconstructing" conquered regions in the South.

In their military analyses of the war, historians traditionally focused largely on marquee battles - Vicksburg, Chancellorsville, Antietam, Gettysburg, and so forth. The primary reason for this focus is obvious - not only did contemporaries consider "decisive battle" the At the tactical level, these large battles involved concentrated encounter among thousands of troops and included the construction of field fortifications and massed assaults, the distribution of individualized use firearms and ammunition (usually rifle muskets) in addition to larger artillery, and the creation of extensive logistical supply lines in many places at once.

However, recent scholarship on the war's "dark" side (the experience of trauma, violence, environmental devastation etc. on the part of ordinary participants) and irregular engagements and alternative theaters (such as the trans-Mississippi West or the commerce raiding battle raging across the world's oceans) have considerably broadened our understanding of the military practice of the war.

Second, are the macro-level

{{< pagebreak >}}

## References
